# Generated by Django 4.1.7 on 2023-03-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
